[package]
name = "three-d"
version = "0.2.0"
authors = ["Asger Nyman Christiansen <asgernyman@gmail.com>"]
edition = "2018"
description = "A renderer which compiles to both desktop (OpenGL) and web (WebAssembly + WebGL)."
license = "MIT"
readme = "README.md"
repository = "https://github.com/asny/three-d"
homepage = "https://asny.github.io/three-d/"
categories = ["graphics", "rendering", "visualization", "wasm", "web-programming"]
keywords = ["3d", "gamedev", "webassembly", "opengl", "webgl"]
exclude = ["/examples", ".gitignore"]

[features]
default = ["glutin-window", "canvas", "3d-io", "image-io"]
glutin-window = ["glutin"] # Default window for desktop (only available when NOT building for the wasm32 architecture)
canvas = ["serde"] # Default window for web (only available when building for the wasm32 architecture)
image-io = ["image"] # Additional image functionality, for example loading an image to a texture
3d-io = ["serde", "bincode"]
no-renderer = [] # Does not include the deferred renderer, but only core OpenGL/WebGL functionality.
debug = [] # Prints OpenGL debug information (only available when NOT building for the wasm32 architecture)

[dependencies]
cgmath = "0.17"
serde = { version = "1.0", features = ["derive"], optional = true }
bincode = { version = "1.2", optional = true }
image = { version = "0.22", optional = true, default-features = false, features = ["gif_codec", "jpeg", "ico", "png_codec", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt"]}

[target.'cfg(not(target_arch = "wasm32"))'.build-dependencies]
gl_generator = {version = "0.14"}

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.glutin]
version = "0.19.0"
optional = true

[target.'cfg(target_arch = "wasm32")'.dependencies.js-sys]
version = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies.wasm-bindgen]
version = "0.2"
features = ['serde-serialize']

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = ['Document', 'Element', 'Node', 'HtmlElement', 'HtmlCanvasElement', 'Window', 'Event', 'MouseEvent',
  'EventTarget', 'WheelEvent', 'KeyboardEvent', 'TouchEvent', 'TouchList', 'Touch','WebGlBuffer','WebGlFramebuffer',
  'WebGl2RenderingContext', 'WebGlProgram', 'WebGlShader', 'WebGlTexture', 'WebGlUniformLocation', 'WebGlVertexArrayObject',
  'WebGlActiveInfo', 'WebGlSync', 'Performance']

[dev-dependencies]
tri-mesh = "0.5.0"